# Generated by Django 5.1.4 on 2025-01-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eno", models.IntegerField()),
                ("ename", models.CharField(max_length=50)),
                ("esal", models.IntegerField()),
                ("eaddr", models.CharField(max_length=200)),
            ],
        ),
    ]
